apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80            # Service port
      targetPort: 80      # Container port
      nodePort: 30036     # Exposed on each Node (must be between 30000-32767)

